southworks/botframework-solutions

lib/typescript/botbuilder-skills/src/models/skillEvents.ts
lib/typescript/botbuilder-skills/src/skillCallingRequestHandler.ts

[TypeScript][WebSocket] Update SkillCallingRequestHandler TS class with its CS counterpart 

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/adapters/customSkillAdapter.ts
templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/adapters/customSkillAdapter.ts

[TypeScript][Skill] Update customSkillAdapter (rename of sampleSkillAdapter)

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/adapters/index.ts
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/index.ts
templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/adapters/index.ts
templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/index.ts

[TypeScript][Skills] Update Startup files

---

sdk/typescript/libraries/botbuilder-solutions/src/feedback/feedbackRecord.ts

 [TypeScript] Migrate feedbackRecord

---

sdk/typescript/libraries/botbuilder-solutions/src/responses/responseManager.ts

 [TypeScript] Migrate responseManager

---

sdk/typescript/libraries/botbuilder-solutions/src/authentication/multiProviderAuthDialog.ts
sdk/typescript/libraries/botbuilder-solutions/src/authentication/oAuthProvider.ts
sdk/typescript/libraries/botbuilder-solutions/src/authentication/oAuthProviderExtensions.ts
sdk/typescript/libraries/botbuilder-solutions/src/authentication/providerTokenResponse.ts

[TypeScript][BotBuilder-Solutions] Update authentication folder

---

sdk/typescript/libraries/botbuilder-solutions/test/dateTimeExtensions.test.js

[TypeScript][BotBuilder-Solutions] Update dateTimeExtensions.test

---

sdk/typescript/libraries/botbuilder-solutions/src/testing/defaultTestAdapter.ts

- Missing accessibility modifier on method definition constructor
- Missing return type on function
- block is empty

[TypeScript][BotBuilder-Solutions] Fix ESLint issues in testing folder

---

sdk/typescript/libraries/botbuilder-solutions/src/dialogs/routerDialog.ts
sdk/typescript/libraries/botbuilder-solutions/src/dialogs/routerDialogTurnResult.ts
sdk/typescript/libraries/botbuilder-solutions/src/dialogs/routerDialogTurnStatus.ts

[TypeScript][BotBuilder-Solutions] Fix ESLint issues in dialogs folder

---

sdk/typescript/libraries/botbuilder-solutions/src/authentication/multiProviderAuthDialog.ts
sdk/typescript/libraries/botbuilder-solutions/src/authentication/oAuthProvider.ts
sdk/typescript/libraries/botbuilder-solutions/src/authentication/providerTokenResponse.ts
sdk/typescript/libraries/botbuilder-solutions/src/dialogs/routerDialog.ts
sdk/typescript/libraries/botbuilder-solutions/src/dialogs/routerDialogTurnResult.ts
sdk/typescript/libraries/botbuilder-solutions/src/dialogs/routerDialogTurnStatus.ts
sdk/typescript/libraries/botbuilder-solutions/src/feedback/feedbackMiddleware.ts
sdk/typescript/libraries/botbuilder-solutions/src/feedback/feedbackOptions.ts
sdk/typescript/libraries/botbuilder-solutions/src/feedback/feedbackRecord.ts
sdk/typescript/libraries/botbuilder-solutions/src/middleware/contentModeratorMiddleware.ts
sdk/typescript/libraries/botbuilder-solutions/src/responses/responseManager.ts
sdk/typescript/libraries/botbuilder-solutions/src/testing/defaultTestAdapter.ts

[TypeScript][BotBuilder-Solutions] Fix ESLint issues

---

sdk/typescript/libraries/botbuilder-solutions/src/dialogs/index.ts
sdk/typescript/libraries/botbuilder-solutions/src/dialogs/routerDialog.ts
sdk/typescript/libraries/botbuilder-solutions/src/dialogs/routerDialogTurnResult.ts
sdk/typescript/libraries/botbuilder-solutions/src/fallbackRequestProvider.ts
sdk/typescript/libraries/botbuilder-solutions/src/index.ts
sdk/typescript/libraries/botbuilder-solutions/src/localesUtils.ts

[TypeScript][BotBuilder-Solutions] Update root files

---

sdk/typescript/libraries/botbuilder-skills/src/auth/microsoftAppCredentialsEx.ts
sdk/typescript/libraries/botbuilder-skills/src/auth/serviceClientCredentials.ts
sdk/typescript/libraries/botbuilder-skills/src/http/skillHttpAdapter.ts
sdk/typescript/libraries/botbuilder-skills/src/http/skillHttpTransport.ts
sdk/typescript/libraries/botbuilder-skills/test/helpers/skillDialogTest.js
sdk/typescript/libraries/botbuilder-skills/test/mocks/mockMicrosoftAppCredentials.js
sdk/typescript/libraries/botbuilder-skills/test/mocks/mockSkillTransport.js
sdk/typescript/libraries/botbuilder-skills/test/skillDialogInvocation.test.js
sdk/typescript/libraries/botbuilder-skills/test/skillDialogSlotFilling.test.js

[TypeScript][BotBuilder-Skills] Fix broken tests

---

sdk/typescript/libraries/botbuilder-skills/src/auth/microsoftAppCredentialsEx.ts
sdk/typescript/libraries/botbuilder-skills/src/auth/serviceClientCredentials.ts
sdk/typescript/libraries/botbuilder-skills/src/http/skillHttpTransport.ts
sdk/typescript/libraries/botbuilder-skills/src/skillDialog.ts
templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/manifestTemplate.json

[TypeScript] Validate BotBuilder-Libraries migration 

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/cognitivemodels.json

[TypeScript][Virtual Assistant Template] Update cognitiveModels.json file

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/dialogs/mainDialog.ts

[TypeScript][Virtual Assistant Template] Update Dialogs Folder

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/adapters/defaultAdapter.ts

[TypeScript][Virtual Assistant Template] Update Adapters folder

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/deploy.ps1
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/update_cognitive_models.ps1

[TypeScript][Virtual Assistant Template] Update deployment scripts folder

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/adapters/customSkillAdapter.ts
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/adapters/defaultAdapter.ts
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/index.ts

[TypeScript][Skill] Update Adapters folder

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/models/skillState.ts

[TypeScript][Skill] Update Models folder

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/locales/de.json
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/locales/en.json
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/locales/es.json
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/locales/fr.json
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/locales/it.json
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/locales/zh.json
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/responses/escalateResponses.ts

[TypeScript] Update Escalate folder and resources

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/dialogs/_mainDialog.ts
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/dialogs/_skillDialogBase.ts
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/dialogs/sampleDialog.ts

[TypeScript][Skill] Update Dialogs folder

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/responses/main/resources/MainResponses.json

[TypeScript][Skill] Update Responses folder

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/test/helpers/botTestBase.js

[TypeScript][Virtual Assistant Sample] Update Test folder

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/cognitivemodels.json

[TypeScript][Skill-Sample] Update cognitivemodels file with 'authoringRegion' field

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/appsettings.json

[TypeScript][Skill] Update appSettings template file

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/index.ts

[TypeScript][Virtual Assistant Template] Update index

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/adapters/defaultAdapter.ts
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/index.ts

[TypeScript][Skill-Sample] Implement whitelistAuthenticationProvider in index.ts and defaultAdapter.ts

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/test/mainDialog.test.js
templates/Virtual-Assistant-Template/typescript/samples/sample-skill/test/mainDialog.test.js

[TypeScript][Skill] Update Tests

---

sdk/typescript/libraries/botbuilder-skills/src/auth/authenticationProvider.ts
sdk/typescript/libraries/botbuilder-skills/src/auth/authenticator.ts
sdk/typescript/libraries/botbuilder-skills/src/auth/msJWTAuthenticationProvider.ts

[TypeScript][Botbuilder-Skills] Update auth folder

---

sdk/typescript/libraries/botbuilder-skills/src/models/skillEvents.ts

[TypeScript][Botbuilder-Skills] Update models folder

---

sdk/typescript/libraries/botbuilder-skills/src/skillException.ts

[TypeScript] Add new enum exceptions

---

sdk/typescript/libraries/botbuilder-skills/src/skillMiddleware.ts

[TypeScript] Implement conversationState Delete on OnTurn method

---

sdk/typescript/libraries/botbuilder-skills/src/dialogs/index.ts
sdk/typescript/libraries/botbuilder-skills/src/dialogs/switchSkillDialog.ts
sdk/typescript/libraries/botbuilder-skills/src/dialogs/switchSkillDialogOptions.ts

[TypeScript] Update dialogs folder

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/skill/templates/sample-skill/src/index.ts
templates/Virtual-Assistant-Template/typescript/samples/sample-skill/src/index.ts

[TypeScript] Parity SkillController

---

sdk/typescript/libraries/botbuilder-skills/src/skillDialog.ts

[TypeScript] Update SkillDialog to botbuilder-skills 0.7

---

sdk/typescript/libraries/botbuilder-solutions/src/middleware/contentModeratorMiddleware.ts
sdk/typescript/libraries/botbuilder-solutions/src/middleware/eventDebuggerMiddleware.ts
sdk/typescript/libraries/botbuilder-solutions/src/middleware/setLocaleMiddleware.ts

[TypeScript] Update middleware folder

---

sdk/typescript/libraries/botbuilder-solutions/src/models/index.ts
sdk/typescript/libraries/botbuilder-solutions/src/models/openDefaultApp.ts
sdk/typescript/libraries/botbuilder-solutions/src/models/sentimentType.ts

[TypeScript] Add models folder

---

sdk/typescript/libraries/botbuilder-solutions/src/cognitiveModelSet.ts

[TypeScript]Update cognitiveModelSet file

---

tools/botskills/src/botskills-connect.ts
tools/botskills/src/utils/index.ts
tools/botskills/src/utils/sanitizationUtils.ts

[Botskills] Implement endpoint validation

---

sdk/typescript/libraries/botbuilder-solutions/test/speechUtility.test.js

Update speechUtility test

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/LU/de-de/general.lu
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/LU/en-us/general.lu
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/LU/es-es/general.lu
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/LU/fr-fr/general.lu
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/LU/it-it/general.lu
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/resources/LU/zh-cn/general.lu
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/LU/de-de/general.lu
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/LU/en-us/general.lu
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/LU/es-es/general.lu
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/LU/fr-fr/general.lu
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/LU/it-it/general.lu
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/resources/LU/zh-cn/general.lu

[TypeScript] Update LU files

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/dialogs/mainDialog.ts
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/dialogs/onboardingDialog.ts
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/dialogs/onboardingDialog.ts

[TypeScript] Parity of Virtual Assistant - Update MainDialog

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/deploy.ps1
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/update_cognitive_models.ps1
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/deploy.ps1
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/deployment/scripts/update_cognitive_models.ps1

[TypeScript] Update deployment scripts

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/adapters/defaultAdapter.ts
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/adapters/defaultAdapter.ts

[TypeScript] Update Adapters folder

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/models/userProfileState.ts
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/models/userProfileState.ts

[TypeScript][Parity] Update Models folder

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/cognitivemodels.json
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/cognitivemodels.json

[TypeScript] Parity of Virtual Assistant - Update cognitivemodels

---

sdk/typescript/libraries/botbuilder-solutions/package-lock.json
sdk/typescript/libraries/botbuilder-solutions/package.json
sdk/typescript/libraries/botbuilder-solutions/src/authentication/multiProviderAuthDialog.ts
sdk/typescript/libraries/botbuilder-solutions/src/skills/skillDialog.ts

[TypeScript] Validate Botbuilder Solutions

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/index.ts
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/src/index.ts

[TypeScript] Parity of Virtual Assistant - Update Startup

---

templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/test/helpers/botTestBase.js
templates/Virtual-Assistant-Template/typescript/samples/sample-assistant/test/helpers/botTestBase.js

[TypeScript] Parity of Virtual Assistant - Update BotTestBase

---

tools/botskills/src/functionality/connectSkill.ts
tools/botskills/src/models/skill.ts

Add property name to ISkill, remove commented code

---

tools/botskills/src/functionality/connectSkill.ts
tools/botskills/src/models/appSetting.ts

Add SkillHostEndpoint property in appsettings

---

tools/botskills/src/functionality/connectSkill.ts

Refactor of executionModel method

---

templates/typescript/samples/sample-skill/test/helpers/skillTestBase.js
templates/typescript/samples/sample-skill/test/interruption.test.js
templates/typescript/samples/sample-skill/test/localization.test.js
templates/typescript/samples/sample-skill/test/mainDialog.test.js
templates/typescript/samples/sample-skill/test/sampleDialog.test.js

[TypeScript][Skill] Update test folder

---

sdk/typescript/libraries/botbuilder-solutions/src/skills/enhancedBotFrameworkSkill.ts
sdk/typescript/libraries/botbuilder-solutions/src/skills/index.ts

Add enhancedBotFrameworkSkill file

---

sdk/typescript/libraries/botbuilder-solutions/src/skills/index.ts
sdk/typescript/libraries/botbuilder-solutions/src/skills/skillsConfiguration.ts

Add skillsConfiguration file

---

sdk/typescript/libraries/botbuilder-solutions/src/skills/index.ts
sdk/typescript/libraries/botbuilder-solutions/src/skills/skillDialogArgs.ts

Add skillDialogArgs file

---

sdk/typescript/libraries/botbuilder-solutions/src/skills/index.ts
sdk/typescript/libraries/botbuilder-solutions/src/skills/skillConversationIdFactory.ts

Add skillConversationIdFactory file

---

sdk/typescript/libraries/botbuilder-solutions/src/skills/skillMiddleware.ts

Update skillMiddleware file

---

templates/typescript/samples/sample-skill/src/index.ts

Startup and Controller changes

[TypeScript] GA SDK Skill Migration - Update Startup and Controller

---

templates/typescript/samples/sample-skill/src/extensions/turnContextEx.ts

[TypeScript] GA SDK Skill Migration - Create Extensions Folder

---

templates/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/authentication/allowedCallersClaimsValidator.ts
templates/typescript/samples/sample-assistant/src/authentication/allowedCallersClaimsValidator.ts

[GA Skills SDK][Virtual Assistant] Create AllowedCallersClaimsValidator

---

templates/typescript/samples/sample-assistant/src/index.ts

[GA Skills SDK][Virtual Assistant] Update SkillController

---

templates/typescript/samples/sample-skill/src/dialogs/mainDialog.ts
templates/typescript/samples/sample-skill/src/dialogs/sampleAction.ts

[GA Skills SDK][Skill] Update Dialogs folder

---

templates/typescript/samples/sample-skill/src/bots/defaultActivityHandler.ts

[TypeScript][0.8] Skill Migration - Update Bots Folder

---

templates/typescript/samples/sample-assistant/src/bots/defaultActivityHandler.ts

[GA Skills SDK][Virtual Assistant] Update DefaultActivityHandler

---

templates/typescript/samples/sample-assistant/src/appsettings.json
templates/typescript/samples/sample-assistant/src/authentication/allowedCallersClaimsValidator.ts
templates/typescript/samples/sample-assistant/src/index.ts
templates/typescript/samples/sample-assistant/src/services/botSettings.ts

[GA Skills SDK][Virtual Assistant] Update index.ts

---

templates/typescript/samples/sample-assistant/src/adapters/defaultAdapter.ts

[GA Skills SDK][Virtual Assistant] Update DefaultAdapter

---

templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts

[GA Skills SDK][Virtual Assistant] Update MainDialog

---

templates/typescript/samples/sample-assistant/src/bots/defaultActivityHandler.ts
templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
templates/typescript/samples/sample-assistant/src/index.ts
templates/typescript/samples/sample-assistant/src/services/botSettings.ts

[GA Skills SDK][Virtual Assistant] Fix ESLint issues

---

templates/typescript/samples/sample-skill/src/bots/defaultActivityHandler.ts
templates/typescript/samples/sample-skill/src/dialogs/mainDialog.ts
templates/typescript/samples/sample-skill/src/extensions/turnContextEx.ts
templates/typescript/samples/sample-skill/src/index.ts
templates/typescript/samples/sample-skill/src/responses/MainResponses.de-de.lg
templates/typescript/samples/sample-skill/src/responses/MainResponses.es-es.lg
templates/typescript/samples/sample-skill/src/responses/MainResponses.fr-fr.lg
templates/typescript/samples/sample-skill/src/responses/MainResponses.it-it.lg
templates/typescript/samples/sample-skill/src/responses/MainResponses.lg
templates/typescript/samples/sample-skill/src/responses/MainResponses.zh-cn.lg

[GA Skills SDK][Skill] Changes to get the Skill working

---

sdk/typescript/libraries/botbuilder-solutions/src/cognitiveModelSet.ts

[GA Skills SDK][BotBuilder-Solutions] Add qnaConfiguration property

---

templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
templates/typescript/samples/sample-assistant/src/dialogs/onboardingDialog.ts
templates/typescript/samples/sample-assistant/src/index.ts
templates/typescript/samples/sample-assistant/src/services/botServices.ts

[GA Skills SDK][Virtual Assistant] Fix build issues

---

sdk/typescript/libraries/botbuilder-solutions/src/middleware/setLocaleMiddleware.ts

[BotBuilder-Solutions] Set default language in SetLocaleMiddleware constructor

---

templates/typescript/samples/sample-assistant/src/services/botServices.ts

Fix botServices' cognitiveModelSet

---

templates/typescript/samples/sample-assistant/src/bots/defaultActivityHandler.ts

Fix call of onMemberAdded

---

templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts

Fix issues found in mainDialog

---

sdk/typescript/libraries/botbuilder-solutions/src/extensions/activityEx.ts

Fix missing type property in activity

---

sdk/typescript/libraries/botbuilder-solutions/src/skills/skillConversationIdFactory.ts

[Typescript][BB Solutions] Fix empty object validation

---

templates/typescript/samples/sample-assistant/src/bots/defaultActivityHandler.ts

[Typescript][GA Skills SDK] Add missing EndOfConversation method

---

sdk/typescript/libraries/botbuilder-solutions/src/dialogs/activityHandlerDialog.ts

[TypeScript][Bot-Solutions]Update ActivityHandlerDialog

---

sdk/typescript/libraries/botbuilder-solutions/src/feedback/resources/FeedbackResponses.zh.json

[TypeScript][Bot-Solutions]Update FeedbackResponses.zh

---

sdk/typescript/libraries/botbuilder-solutions/src/authentication/multiProviderAuthDialog.ts

[TypeScript][Bot-Solutions] Update MultiProviderAuthDialog

---

sdk/typescript/libraries/botbuilder-solutions/src/skills/dialogs/switchSkillDialogOptions.ts

[TypeScript][Bot-Solutions] Update SwitchSkillDialogOptions

---

sdk/typescript/libraries/botbuilder-solutions/test/mocha.opts
sdk/typescript/libraries/botbuilder-solutions/test/responses/languageGeneration.test.js
sdk/typescript/libraries/botbuilder-solutions/test/responses/responseGeneration.test.js
sdk/typescript/libraries/botbuilder-solutions/test/responses/speechUtility.test.js

[TypeScript][Bot-Solutions] Update Responses folder

---

templates/typescript/samples/sample-skill/src/manifests/manifest-1.0.json
templates/typescript/samples/sample-skill/src/manifests/manifest-1.1.json

[0.8][Sample Skill] Add new manifests and default.htm

---

sdk/typescript/libraries/bot-solutions/README.md

Currently, `Bot-Solutions` doesn't contain a README to explain how to use the library.
Add a `README` following the SDK structure.
\-
\-

[Documentation][Bot-Solutions] Add README

---

sdk/typescript/libraries/bot-solutions/src/dialogs/eventPrompt.ts
sdk/typescript/libraries/bot-solutions/src/dialogs/interruptableDialog.ts
sdk/typescript/libraries/bot-solutions/src/dialogs/interruptionAction.ts

[TypeScript][Bot Solutions] Update dialogs folder

---

sdk/typescript/libraries/bot-solutions/src/middleware/contentModeratorMiddleware.ts

[TypeScript][Bot-Solutions] Remove language from screenResult initialization

---

sdk/typescript/libraries/bot-solutions/src/authentication/authenticationResponses.ts
sdk/typescript/libraries/bot-solutions/src/authentication/multiProviderAuthDialog.ts
sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.de.json
sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.es.json
sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.fr.json
sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.it.json
sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.json
sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.zh.json

[TypeScript][Bot-Solutions] Migrate Authentication folder

---

sdk/typescript/libraries/bot-solutions/src/proactive/proactiveStateMiddleware.ts

[TypeScript][Bot-Solutions] Simplify role validation

---

sdk/typescript/libraries/bot-solutions/src/feedback/feedbackMiddleware.ts
sdk/typescript/libraries/bot-solutions/src/feedback/feedbackOptions.ts
sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.de.json
sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.es.json
sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.fr.json
sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.it.json
sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.json
sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.zh.json

[TypeScript][Bot Solutions] Update Feedback folder

---

sdk/typescript/libraries/bot-solutions/test/proactive/proactive.test.js

[TypeScript][Bot-Solutions] Migrate ProactiveTests

---

sdk/typescript/libraries/bot-solutions/test/responses/languageGeneration.test.js

[TypeScript][Bot-Solutions] Migrate LanguageGeneration Tests

---

templates/typescript/samples/sample-assistant/src/appsettings.json
templates/typescript/samples/sample-assistant/src/index.ts

[TypeScript][Virtual Assistant] Update root folder

---

templates/typescript/samples/sample-assistant/deployment/scripts/deploy.ps1
templates/typescript/samples/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
templates/typescript/samples/sample-assistant/deployment/scripts/luis_functions.ps1
templates/typescript/samples/sample-assistant/deployment/scripts/update_cognitive_models.ps1

Change PowerShell script from deployment scripts folder to match v1.0

[TypeScript][Virtual Assistant] Parity V.A. PowerShell Deploy Scripts

---

templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts

Add changes to TypeScript Virtual Assistant mainDialog.ts file to match version 1.0 from C#

[TypeScript][Virtual Assistant]Add changes to mainDialog.ts to match v1.0

---

templates/typescript/samples/sample-assistant/src/dialogs/onboardingDialog.ts

Add change to onboardingDialog.ts to match version 1.0 from C#

[TypeScript][Virtual Assistant] Add change to onboardingDialog.ts to match v1.0

---

templates/typescript/samples/sample-assistant/src/index.ts
templates/typescript/samples/sample-assistant/src/services/botSettings.ts
templates/typescript/samples/sample-assistant/src/tokenExchange/ITokenExchangeConfig.ts
templates/typescript/samples/sample-assistant/src/tokenExchange/index.ts
templates/typescript/samples/sample-assistant/src/tokenExchange/tokenExchangeConfig.ts

[TypeScript][Virtual Assistant]Port botSettings and add tokenExchange folder

---

templates/typescript/samples/sample-assistant/src/services/botServices.ts

Add the changes for parity to botservices class

[TypeScript][Virtual Assistant] Add botservices parity

---

templates/typescript/samples/sample-assistant/test/helpers/botTestBase.js
templates/typescript/samples/sample-assistant/test/interruption.test.js
templates/typescript/samples/sample-assistant/test/localization.test.js
templates/typescript/samples/sample-assistant/test/mainDialog.test.js
templates/typescript/samples/sample-assistant/test/onboardingDialog.test.js

[TypeScript][Virtual Assistant] Add test folder

---

templates/typescript/samples/sample-skill/src/adapters/defaultAdapter.ts

Add changes to defaultAdapter.ts to match v1.0

[TypeScript][Skill] defaultAdapter.ts changes

---

templates/typescript/samples/sample-skill/src/appsettings.json
templates/typescript/samples/sample-skill/src/cognitivemodels.json
templates/typescript/samples/sample-skill/src/index.ts

Add the changes to the files in the root folder of the TS Skill to port it to v1.0

[TypeScript][Skill] Add v1.0 changes in root folder

---

templates/typescript/samples/sample-skill/src/authentication/allowedCallersClaimsValidator.ts
templates/typescript/samples/sample-skill/src/authentication/index.ts

Add AllowedCallersClaimValidator class and corresponding index file

[TypeScript][Skill] Add allowedCallersClaimsValidator.ts and index

---

templates/typescript/samples/sample-skill/src/bots/defaultActivityHandler.ts
templates/typescript/samples/sample-skill/src/index.ts

Add v1.0 changes to **DefaultActivityHandler** class

[TypeScript][Skill]Add changes to defaultActivityHandler.ts

---

templates/typescript/samples/sample-skill/deployment/scripts/deploy.ps1
templates/typescript/samples/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
templates/typescript/samples/sample-skill/deployment/scripts/luis_functions.ps1

Update all the deployment scripts from the TS Skill bot to v1.0

[TypeScript][Skill] Deployment Scripts

---

templates/typescript/samples/sample-skill/src/dialogs/mainDialog.ts

Add changes to MainDialog class to port to v1.0

[TypeScript][Skill]Main Dialog

---

templates/typescript/samples/sample-skill/src/extensions/turnContextEx.ts

[TypeScript][1.0] TurnContextEx Migration - Remove the casting of the BotAdapter

---

templates/typescript/samples/sample-skill/src/dialogs/sampleAction.ts
templates/typescript/samples/sample-skill/src/index.ts

Changes applied to sampleAction.ts file

[TypeScript][Skill]Port sampleAction file

---

templates/typescript/samples/sample-skill/src/dialogs/sampleAction.ts
templates/typescript/samples/sample-skill/src/dialogs/sampleDialog.ts
templates/typescript/samples/sample-skill/src/dialogs/skillDialogBase.ts

Add changes to skillDialogBase to match v1.0.
- skillDialogBase.ts
- sampleAction.ts
- sampleDialog.ts

[TypeScript][Skill]Add v1.0 changes to skillDialogBase and derived classes

---

templates/typescript/samples/sample-skill/package-lock.json
templates/typescript/samples/sample-skill/package.json
templates/typescript/samples/sample-skill/test/helpers/skillTestBase.js

[TypeScript][1.0] Update SkillTestBase class

---

templates/typescript/samples/sample-skill/src/services/botServices.ts

Changes added to botServices.ts to match v1.0 for Skill bot

[TypeScript][Skill] Migration changes to botServices.ts

---

templates/typescript/samples/sample-assistant/.eslintrc.json

[TypeScropt][Virtual Assistant] Update eslint rule

---

templates/typescript/samples/sample-skill/src/adapters/defaultAdapter.ts
templates/typescript/samples/sample-skill/src/dialogs/sampleDialog.ts
templates/typescript/samples/sample-skill/src/index.ts
templates/typescript/samples/sample-skill/src/services/botServices.ts
templates/typescript/samples/sample-skill/src/services/botSettings.ts

Fix errors that showed up when using latest bot solutions (1.0.0)

[TypeScript][Skill]Fixes for latest bot-solutions compat

---

templates/typescript/samples/sample-assistant/test/helpers/botTestBase.js

[TypeScript][1.0] Remove unused libraries

---

templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/test/helpers/botTestBase.js

[TypeScript][1.0] Remove unnecessary dependencies from template

---

templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/_.eslintrc.json
templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/_package.json

- Add botbuilder-lg to package.json
- Replace outdated ESLint rule

[TypeScript][1.0] Update skill template

---

templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/tokenExchange/tokenExchangeSkillHandler.ts
templates/typescript/samples/sample-assistant/src/tokenExchange/tokenExchangeSkillHandler.ts

[TypeScript][Virtual Assistant Sample] Fixing inverted parameters in TokenExchangeSkillHandler.ts

---

docs/_docs/virtual-assistant/handbook/testing.md

Fix 3622
The [/virtual-assistant/handbook/testing/](https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/testing/) document was outdated.
- Update Unit Testing section showing where the unit tests are available in the repository
- Update Bot Framework Emulator section explaining how to use the populated appsettings.json file testing the bot in Emulator
\-
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any …

[Documentation] Improve Testing documentation

---

templates/typescript/generator-bot-virtualassistant/test/generator-bot-virtualassistant.test.suite.js

The `locale` folder was removed, but the test wasn't.
We removed the test which checks if the `locale` folder exists.

[TypeScript][Generator] Fix broken tests

---

samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/Nightly-Dotnet-VirtualAssistantToSkill.yml
samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/README.md

Adds a YAML file with the configuration for the C# Virtual Assistant sample functional tests pipeline
Adds a new YAML file

[C#][Virtual Assistant] Add yaml file for C# Virtual Assistant sample functional tests

---

samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
samples/csharp/skill/SkillSample/SkillSample.csproj
sdk/csharp/libraries/microsoft.bot.solutions/Microsoft.Bot.Solutions.csproj
templates/csharp/Skill/Skill/Skill.csproj
templates/csharp/VA/VA/VA.csproj

Fixes XXXX
The last version published of BF SDK C# is 4.11.1
- Update the .csproj files to use 4.11.1 for the BF libraries for C# solutions
Yes, it was tested manually and validated the build and tests execution of the packages.

[C#] Update BF SDK versions to 4.11.1

---

templates/typescript/samples/sample-assistant/functional-tests/README.md
templates/typescript/samples/sample-assistant/functional-tests/VirtualAssistantSample.FunctionalTests/DirectLineClientTests.cs
templates/typescript/samples/sample-assistant/functional-tests/sample-assistant.yml

Apply the feedback of PR #3542

[TypeScript][Virtual Assistant] Apply feedback of PR 3542

---

templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/bots/defaultActivityHandler.ts
templates/typescript/samples/sample-assistant/src/bots/defaultActivityHandler.ts

[TypeScript][Virtual Assistant] Replace DialogEx using JS SDK DialogHelper

---

templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/bots/defaultActivityHandler.ts
templates/typescript/samples/sample-skill/src/bots/defaultActivityHandler.ts

[TypeScript][Skill] Replace DialogEx using JS SDK DialogHelper

---

templates/typescript/samples/sample-assistant/functional-tests/README.md
templates/typescript/samples/sample-assistant/functional-tests/VirtualAssistantSample.FunctionalTests/DirectLineClientTests.cs
templates/typescript/samples/sample-assistant/functional-tests/sample-assistant.yml
templates/typescript/samples/sample-skill/functional-tests/README.md
templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
templates/typescript/samples/sample-skill/functional-tests/sample-skill.yml

[TypeScript][VA & Skill] Add Skill connection in the VA's Functional Test - Apply feedback of PR 3542

---

samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/Nightly-Dotnet-VirtualAssistantToSkill.yml
samples/csharp/skill/SkillSample.FunctionalTests/SkillSample.yml
templates/typescript/samples/sample-assistant/functional-tests/sample-assistant.yml
templates/typescript/samples/sample-skill/functional-tests/sample-skill.yml
tools/botskills/botskills.functionalTest/nightly-botskills.yml

We clean the yaml files for the functional tests pipeline by removing unnecessary steps and re-ordering them
- Add missing steps for the clean of the resources
- Remove unnecessary steps
- Remove duplicate `failOnStderr` from steps

[Functional Test] Clean yaml files

---

samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/README.md
samples/csharp/skill/SkillSample.FunctionalTests/README.md
templates/typescript/samples/sample-assistant/functional-tests/README.md
templates/typescript/samples/sample-skill/functional-tests/README.md

[Documentation] Update Functional Test documents to follow SDK approach

---

docs/_docs/solution-accelerators/tutorials/enable-continuous-deployment/3-configure-pipeline.md

[Documentation] Add step to install BotSkill CLI tool in the configuration pipelines doc

---

docs/_data/button.yml
docs/_docs/clients-and-channels/tutorials/enable-speech/4-integrate-speech-channel.md

Related to 3689
The [clients-and-channels](https://github.com/microsoft/botframework-solutions/tree/master/docs/_docs/clients-and-channels) section of the public documentation is outdated
- Fix broken links
The updated files are the followings:
- docs/_data/button.yml
- docs/_docs/clients-and-channels/tutorials/enable-speech/4-integrate-speech-channel.md
It was rendered manually in order to check the result of the changes
*Are there any remaining steps or dependencies before this issue can be fully …

[Documentation] Update Clients and Channels section

---

templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/resources/parameters.template.json
templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/resources/template.json
templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/deploy.ps1
templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/luis_functions.ps1
templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/update_cognitive_models.ps1
templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/resources/parameters.template.json
templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/resources/template.json
templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/deploy.ps1
templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/luis_functions.ps1
templates/typescript/samples/sample-assistant/deployment/resources/parameters.template.json
templates/typescript/samples/sample-assistant/deployment/resources/template.json
templates/typescript/samples/sample-assistant/deployment/scripts/deploy.ps1
templates/typescript/samples/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
templates/typescript/samples/sample-assistant/deployment/scripts/luis_functions.ps1
templates/typescript/samples/sample-assistant/deployment/scripts/update_cognitive_models.ps1
templates/typescript/samples/sample-skill/deployment/resources/parameters.template.json
templates/typescript/samples/sample-skill/deployment/resources/template.json
templates/typescript/samples/sample-skill/deployment/scripts/deploy.ps1
templates/typescript/samples/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
templates/typescript/samples/sample-skill/deployment/scripts/luis_functions.ps1

Fix 3772
The TypeScripts deployment scripts and ARM templates are out-of-date.
Update the TypeScript scripts and ARM templates to be in parity with C#. Also, we included some bug-fixes/improvements that are present in the PRs of 1.0 TypeScript and in `next` branch.
The deployment was correctly tested manually and the communication was tested as expected.
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or …

[TypeScript][Samples & Templates] Update Deployment Scripts and ARM Templates

---

samples/android/clients/EventCompanion/readme.md
samples/csharp/assistants/enterprise-assistant/README.md
sdk/typescript/libraries/bot-solutions/README.md
templates/csharp/Skill/Skill/readme.md
templates/csharp/VA/VA/readme.md
templates/typescript/generator-bot-virtualassistant/README.md
templates/typescript/generator-bot-virtualassistant/generators/app/README.md
templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/README.md
templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/pipeline/README.md
templates/typescript/generator-bot-virtualassistant/generators/skill/README.md
templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/README.md
templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/pipeline/README.md
templates/typescript/samples/sample-assistant/README.md
templates/typescript/samples/sample-assistant/pipeline/README.md
templates/typescript/samples/sample-skill/README.md
templates/typescript/samples/sample-skill/pipeline/README.md
tools/botskills/README.md
tools/botskills/docs/commands/connect.md
tools/botskills/docs/commands/disconnect.md
tools/botskills/docs/commands/list.md
tools/botskills/docs/commands/migrate.md
tools/botskills/docs/commands/refresh.md
tools/botskills/docs/commands/update.md

Related to 3689
The [public internal document](https://github.com/microsoft/botframework-solutions) is outdated
- Improve documents
- Remove empty documents
- Have parity between botskills' documents
- Fix broken links
The updated files are the followings:
- samples/android/clients/EventCompanion/readme.md
- samples/csharp/assistants/enterprise-assistant/README.md
- sdk/typescript/libraries/bot-solutions/README.md
- templates/csharp/README.md
- templates/csharp/Skill/Skill/readme.md
- templates/csharp/VA/VA/readme.md
- …

[Documentation] Update internal documentation

---

docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models.md

Fix 3765
The document [virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models/
](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models/) does not explain clearly the necessary code changes to include a new knowledge base into the Virtual Assistant.
We detailed step by step the necessary changes to include a new Knowledge Base into the Virtual Assistant.
The document was manually rendered.
*Are there any remaining steps or dependencies before this issue can …

[Documentation] Detail the code changes after adding a new Knowledge Base

---

templates/typescript/generator-bot-virtualassistant/package-lock.json
templates/typescript/generator-bot-virtualassistant/package.json
tools/botskills/package-lock.json

Related to 3570
Vulnerabilities were found on the dependencies of the `generator-bot-virtualassistant` and `botskills`.
We identified that merged in `master` branch, we are replicating this into `next` and adding the necessary fixes for the generator.
Update [lodash](https://lodash.com/) dependency to `4.17.19` in `generator-bot-virtualassistant` and `botskills`
We manually confirmed that these updates doesn't affect to the behavior of each component
*Are there any remaining steps or dependencies …

[Generator & Botskills] Fix dependencies' vulnerabilities

---

samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
samples/csharp/skill/SkillSample/SkillSample.csproj
sdk/csharp/libraries/microsoft.bot.solutions/Microsoft.Bot.Solutions.csproj
sdk/csharp/tests/microsoft.bot.solutions.tests/Skills/SkillConversationIdFactoryTests.cs
sdk/csharp/tests/microsoft.bot.solutions.tests/TaskExtensionTests/BackgroundWorkerTests.cs
sdk/csharp/tests/microsoft.bot.solutions.tests/Util/UtilTests.cs

[C#] Update dependencies and imports

---

samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Startup.cs
samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Startup.cs
samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Startup.cs
samples/csharp/skill/SkillSample/Adapters/DefaultAdapter.cs
samples/csharp/skill/SkillSample/Startup.cs
templates/csharp/Skill/Skill/Adapters/DefaultAdapter.cs
templates/csharp/Skill/Skill/Startup.cs
templates/csharp/VA/VA/Adapters/DefaultAdapter.cs
templates/csharp/VA/VA/Startup.cs

Remove qualified names

---

templates/csharp/Skill/Skill/Services/BotServices.cs
templates/csharp/Skill/Skill/Services/BotSettings.cs
templates/csharp/Skill/Skill/SkillProjectTemplate.vstemplate
templates/csharp/Skill/Skill/Startup.cs
templates/csharp/Skill/Skill/appsettings.json
templates/csharp/VA/VA.Tests/BotTestBase.cs
templates/csharp/VA/VA.Tests/VA.Tests.csproj
templates/csharp/VA/VA/Bots/DefaultActivityHandler.cs
templates/csharp/VA/VA/Dialogs/MainDialog.cs
templates/csharp/VA/VA/Extensions/InvokeActivityExtensions.cs
templates/csharp/VA/VA/Extensions/InvokeResponseExtensions.cs
templates/csharp/VA/VA/Models/SkillCardActionData.cs
templates/csharp/VA/VA/Services/BotServices.cs
templates/csharp/VA/VA/Services/BotSettings.cs
templates/csharp/VA/VA/Startup.cs
templates/csharp/VA/VA/VA.csproj
templates/csharp/VA/VA/VAProjectTemplate.vstemplate
templates/csharp/VA/VA/appsettings.json

The C# Virtual Assistant Template and Skill Template doesn't contain the latest changes of the samples
Replicate PR 3426 and PR 3569 to Virtual Assistant Template and Skill Template
_All the tests passed correctly in the Virtual Assistant and Skill_
\-

[C#][VA/Skill] Replicate changes of Samples to Templates
