southworks/botframework-solutions

sdk/typescript/libraries/botbuilder-solutions/src/middleware/contentModeratorMiddleware.ts
=> [TypeScript][BotBuilder-Solutions] ContentModeratorMiddleware parity with C#

sdk/typescript/libraries/botbuilder-solutions/src/testing/defaultTestAdapter.ts
=> [TypeScript][BotBuilder-Solutions] Add DefaultTestAdapter class

sdk/typescript/libraries/botbuilder-solutions/src/dialogs/routerDialog.ts, sdk/typescript/libraries/botbuilder-solutions/src/dialogs/routerDialogTurnResult.ts, sdk/typescript/libraries/botbuilder-solutions/src/dialogs/routerDialogTurnStatus.ts
- Add routerDialogTurnResult.ts
- Add routerDialogTurnStatus.ts
- Implementation on routerDialog.ts
=> [TypeScript][BotBuilder-Solutions] Parity with C# of 'dialogs' folder and implementation on 'routerDialog'

sdk/typescript/libraries/botbuilder-skills/src/auth/authHelpers.ts, sdk/typescript/libraries/botbuilder-skills/src/auth/authenticationProvider.ts, sdk/typescript/libraries/botbuilder-skills/src/auth/authenticator.ts, sdk/typescript/libraries/botbuilder-skills/src/auth/index.ts, sdk/typescript/libraries/botbuilder-skills/src/auth/msJWTAuthenticationProvider.ts, sdk/typescript/libraries/botbuilder-skills/src/auth/serviceClientCredentials.ts, sdk/typescript/libraries/botbuilder-skills/src/auth/whitelistAuthenticationProvider.ts
=> [TypeScript][BotBuilder-Skills] Update Auth folder

sdk/typescript/libraries/botbuilder-solutions/test/dateTimeExtensions.test.js
_What is the context of this pull request? Why is it being done?_
Fix the bugs of `Tests` to that everything works as it should.
_Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)_
Fixed the errors of `Tests`.
Some tests that were fixed are:
_Is this covered by existing tests or new ones? If no, why not?_
Yes, it's covered by the tests.
1. Go to `.\sdk\typescript\libraries\botbuilder-solutions`.
2. Open a terminal in that location and execute `npm install`.
3. Run `npm run build`.
4. Then run `npm run test` and check that everything is alright.
_Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull …
=> [TypeScript][BotBuilder-Solution] Fix date time extensions tests

sdk/typescript/libraries/botbuilder-skills/test/helpers/skillDialogTest.js
=> [TypeScript] Update SkillDialogTest to botbuilder-skills 0.7

sdk/typescript/libraries/botbuilder-solutions/src/authentication/multiProviderAuthDialog.ts
=> [TypeScript] Migrate multiproviderauthdialog

sdk/typescript/libraries/botbuilder-solutions/src/extensions/luisRecognizerEx.ts, sdk/typescript/libraries/botbuilder-solutions/test/helpers/skillLuis.js, sdk/typescript/libraries/botbuilder-solutions/test/listEx.test.js, sdk/typescript/libraries/botbuilder-solutions/test/luisRecognizeEx.test.js
=> [TypeScript] Add tests for LUIS recognizer extension method

sdk/typescript/libraries/botbuilder-solutions/test/languageGeneration.test.js, sdk/typescript/libraries/botbuilder-solutions/test/responses/testResponses.es.lg, sdk/typescript/libraries/botbuilder-solutions/test/responses/testResponses.lg
=> [TypeScript] Add tests for Template Engine

tools/botskills/src/botskills-connect.ts, tools/botskills/src/botskills-update.ts, tools/botskills/src/functionality/connectSkill.ts, tools/botskills/src/models/connectConfiguration.ts, tools/botskills/src/models/updateConfiguration.ts
=> [TypeScript] Implement endpointName parameter for Botskills

tools/botskills/test/refresh.test.js
=> [Botskills] Fix refresh when the dispatch external calls fails

templates/typescript/samples/sample-skill/src/dialogs/mainDialog.ts, templates/typescript/samples/sample-skill/test/helpers/skillTestBase.js
=> [TypeScript][Skill] Fix botbuilder-skills references

tools/botskills/src/botskills-disconnect.ts
Related to 3489
The disconnect command of botskills only checks for the id, not the name.
We changed the description to show what Botskills actually need to remove a Skill, that is the `id` of the Skill.
\-
\-
=> [Botskills] Update disconnect command description

sdk/typescript/libraries/bot-solutions/tsconfig.json, templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/tsconfig.json, templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/tsconfig.json, templates/typescript/samples/sample-assistant/tsconfig.json, templates/typescript/samples/sample-skill/tsconfig.json
Solve 3630
With the last version of the SDK 4.10.0, the compilation of the TypeScript solutions raises an issue related to types missing for [@microsoft/recognizers-text-data-types-timex-expression](https://www.npmjs.com/package/@microsoft/recognizers-text-data-types-timex-expression) library
Remove the `strict` check in `tsconfig` files for Virtual Assistant (Sample & Template), Skill (Sample & Template) and Bot-Solutions
Yes, it was tested manually 
*Are there any remaining steps or dependencies …
=> [TypeScript] Remove strict check in tsconfig files

tools/botskills/src/functionality/listSkill.ts, tools/botskills/src/utils/index.ts, tools/botskills/src/utils/sanitizationUtils.ts
Fix 3588
BotSkills _list_ command would erroneously list no connected bots when applied to bots connected with BotSkills versions prior to 1.0.16, due to a casing change in properties name.
Functionality of the _list_ command was modified to accept the **BotFrameworkSkills** property in both upper and lower camel case format as not to break compatibility with older versions.
**Changed files:**
- listSkill.ts
*Are there any remaining steps or dependencies before this issue can be fully resolved? If …
=> [BotSkills] Sanitize appsettings skills properties to be case insensitive for list command

docs/_docs/skills/tutorials/add-prebuilt-skill/4-update-skill-manifest.md, docs/_docs/skills/tutorials/add-prebuilt-skill/5-connect-skill.md, docs/_docs/skills/tutorials/add-prebuilt-skill/6-test-your-skill.md, docs/_docs/skills/tutorials/add-prebuilt-skill/7-next-steps.md
Fix 3645
After the [/skills/tutorials/add-prebuilt-skill/3-deploy-skill-project/](https://microsoft.github.io/botframework-solutions/skills/tutorials/add-prebuilt-skill/3-deploy-skill-project/) document need a step to explain how to update the Skill Manifest before connecting the Skill to the Virtual Assistant.
- Change the position of some documents
- Add the `4-update-skill-manifest` document
\-
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe …
=> [Documentation] Add Update Skill Manifest document

docs/_docs/skills/tutorials/create-skill/csharp/5-update-manifest.md, docs/_docs/skills/tutorials/create-skill/typescript/5-update-manifest.md, docs/_docs/skills/tutorials/create-skill/typescript/6-run-your-skill.md, docs/_docs/skills/tutorials/create-skill/typescript/7-add-your-skill.md, docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/5-run-your-assistant.md
Fix 3638
The documentation [TypeScript Update your Skill Manifest](https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/typescript/5-update-manifest/), [C# Update your Skill Manifest](https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/5-update-manifest/) and [TypeScript Add your skill to a Virtual Assistant](https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/typescript/5-update-manifest/) presents ambiguities described in the issue 3638.
- Explain the values of some …
=> [Documentation] Fix ambiguities of TypeScript and C# documentation for manifests

samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/publish.ps1, samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Scripts/publish.ps1, samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/publish.ps1, samples/csharp/skill/SkillSample/Deployment/Scripts/publish.ps1, templates/csharp/Skill/Skill/Deployment/Scripts/publish.ps1, templates/csharp/VA/VA/Deployment/Scripts/publish.ps1, templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/publish.ps1, templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/publish.ps1, templates/typescript/samples/sample-assistant/deployment/scripts/publish.ps1, templates/typescript/samples/sample-skill/deployment/scripts/publish.ps1
Fix MS3581
All assistant and skill bots would fail to publish during the deployment process, when done so from a folder containing white spaces in its path.
We wrapped in quotes the path to the zip at the az CLI deployment line inside the `publish.ps1` of the following components:
- TypeScript Virtual Assistant Sample/Template
- TypeScript Skill Sample/Template
- C# Virtual Assistant Sample/Template
- C# Skill Sample/Template
- C# Enterprise Assistant
- C# Hospitality Assistant
All tests remained …
=> [Virtual Assistant][Skill] Wrap with quotes the zip in the publish scripts

templates/typescript/generator-bot-virtualassistant/generators/skill/src/copier.js, templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/test/mocks/resources/cognitiveModels.json, templates/typescript/generator-bot-virtualassistant/test/generator-bot-virtualassistant.skill.test.suite.js
Closes the PR#XXXX
The generator was creating skills with failing tests when the name of the skill was different to `sample-skill`.
As the test values are mocked we added the `sampleSkill` value as the name and id of the skill in the tests.
_Generator's tests_
_TypeScript Skill tests_
\-
\-
=> [TypeScript][Skill] Fix cognitivemodel mocks values

samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/TokenExchange/TokenExchangeSkillHandler.cs
Related to 3654 and 3655.
Parameters on `TokenExchangeSkillHandler.cs` need to be inverted since we need the ConnectionName before the Id following [IExtendedUserTokenProvider](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/OAuth/IExtendedUserTokenProvider.cs#L138)
We updated the `TokenExchangeSkillHandler.cs` with the inverted parameters following the signature of `ExchangeTokenAsync`.
\-
*Are there any remaining steps or dependencies before this issue can …
=> [C#][Virtual Assistant Sample] Fixing inverted parameters in TokenExchangeSkillHandler.cs

templates/csharp/Skill/Skill/SkillProjectTemplate.vstemplate
Fix 3673
The `$safeprojectname$` variable is not replaced correctly in the _[SkillSample].yml_ file of the Pipeline Folder when a Skill project is created using the VSIX.
We made a change in the file `SkillProjectTemplate.vstemplate`. In the section **Folder Name Pipeline**, configured the parameter `ReplaceParameters` in true.
=> [C#][VSIX] Fix template placeholder not correctly replaced in Skill yml file

docs/_docs/overview/virtual-assistant-template.md
Solve 3672
The [/overview/virtual-assistant-template/](https://microsoft.github.io/botframework-solutions/overview/virtual-assistant-template/) has broken links and is outdated.
- Fix broken links
- Update documentation with the new version of the Virtual Assistant Template/Sample
=> [Documentation] Update /overview/virtual-assistant-template/ and fix broken links

sdk/typescript/libraries/bot-solutions/src/authentication/multiProviderAuthDialog.ts, sdk/typescript/libraries/bot-solutions/src/botSettingsBase.ts
Fix disparity between C# and TS implementation
- Add the missing parameter `outhCredentials` in the `getTokenStatus` method in the `multiProviderAuthDialog` class
All unit tests passed successfully
=> [TypeScript][Bot-Solutions] Add the missing parameter outhCredentials in getTokenStatus method in multiProviderAuthDialog class

tools/botskills/botskills.functionalTest/nightly-botskills.yml, yaml/deploySteps.yml
Some PowerShell tasks that beyond deploying include an az login using credentials that the user needs to set as variables in the pipeline.
To solve this, we could instead use an Azure CLI v2 task which supports both az CLI and PowerShell as languages, and authenticates automatically using an Azure Subscription
- Change powershell tasks to Azure CLI v2 tasks
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests …
=> [Functional Test] Improvements on Functional Tests

templates/typescript/samples/sample-skill/functional-tests/sample-skill.yml, tools/botskills/botskills.functionalTest/nightly-botskills.yml, yaml/dotnetBuildSteps.yml
The dotnet restore step is not necessary since dotnet build step already does it
- Remove the dotnet restore step from all the yaml files
=> [Functional Tests] Remove the dotnet restore steps

templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/bots/_defaultActivityHandler.ts, templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/test/localization.test.js, templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/test/mainDialog.test.js, templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/bots/defaultActivityHandler.ts, templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/test/localization.test.js, templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/test/mainDialog.test.js, templates/typescript/samples/sample-assistant/src/bots/defaultActivityHandler.ts, templates/typescript/samples/sample-assistant/test/localization.test.js, templates/typescript/samples/sample-assistant/test/mainDialog.test.js, templates/typescript/samples/sample-skill/src/bots/defaultActivityHandler.ts, templates/typescript/samples/sample-skill/test/localization.test.js, templates/typescript/samples/sample-skill/test/mainDialog.test.js
Fixes 3731
What is the context of this pull request? Why is it being done?
An issue was found where duplicated messages would arrive when contacting the TypeScript V.A. or Skill throught Direct Line. To fix this we implemented a validation taking as a reference the behavior in the sample bots.
Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)
We added a validation to the membersAdded method in both the Virtual Assistant and Skill to only deliver the message when it's due to the user.
Is this covered by existing tests or new ones? If no, why not?
Tests have been adapted and are passing in both the V.A. and Skill
Are there any remaining steps or dependencies before this issue can …
=> [TypeScript][Virtual Assistant & Skill] Fix duplicated messages when communicating through DirectLine

sdk/csharp/libraries/microsoft.bot.solutions/BotSettingsBase.cs, sdk/csharp/libraries/microsoft.bot.solutions/Services/ConnectedService.cs, sdk/csharp/libraries/microsoft.bot.solutions/Services/LuisService.cs, sdk/csharp/libraries/microsoft.bot.solutions/Services/QnAMakerService.cs, sdk/csharp/libraries/microsoft.bot.solutions/Services/ServiceTypes.cs
Solves 3617
With the new [botbuilder@4.10.0-rc1](https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder/4.10.0-rc1) packages, the LuisService class has been deprecated so Bot-Solutions doesn't build as it runs into a "LuisService is obsolete: This class is deprecated" error.
We added the `[System.Obsolete]` tag to fix the deprecation error, so that Bot-Solutions builds.
We tested the C# solutions, after apply this fix, manually and worked as expected.
_Fix …
=> [C#][Bot-Solutions] Add System.Obsolete in the LuisService implementation of BotSettingsBase

tools/botskills/src/functionality/connectSkill.ts, tools/botskills/test/connect.test.js
Port #3262 
At the moment, when botskills processes multiple languages and an error occurs while parsing LU files it will stop processing any subsequent LU file, therefore no further error will be logged.
With these changes, when there is an issue while parsing multiple languages with Ludown it will show all the error messages if there are issues with more than one, instead of showing only the first error message.
The exception throwing in `executeLudownParse` and `executeDispatchAdd` is changed to error loging.
After processing each language, if there was an …
=> [PORT #3262][Botskills] Show all language output when there's an issue with a LU file

templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/index.ts, templates/typescript/samples/sample-assistant/src/index.ts
When trying to run the TypeScript Virtual Assistant without a Skill connected, an assertion error is raised, pointing that "The expression evaluated to a falsy value: assert_1.ok(allowedCallers.length)" because of the caller claims are [empty](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botframework-connector/src/auth/allowedCallersClaimsValidator.ts#L17).
- New validation to check if the Virtual Assistant has skills connected or not to complete the caller claims
- Replicate to template
The TypeScript Virtual Assistant communication worked as …
=> [TypeScript][Virtual Assistant] Add claim's validation if the VA is not connected to Skills

templates/typescript/samples/sample-assistant/package-lock.json, templates/typescript/samples/sample-skill/package-lock.json
As the TypeScirpt [bot-solutions@1.1.0](https://www.npmjs.com/package/bot-solutions/v/1.1.0) was published in npmjs, the `package-lock.json` files of the Virtual Assistant Sample and Skill Sample should be consume the new version
- Regenerate the `package-lock.json` file of the Virtual Assistant Sample in TypeScript
- Regenerate the `package-lock.json` file of the Skill Sample in TypeScript
The compilation and the unit tests worked correctly
_Unit tests passing in the TypeScript Virtual Assistant …
=> [TypeScript][Samples] Update package-lock to consume last version of bot-solutions 1.1.0
